version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_DATABASE: user_auth_db,cinema_movie_db
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3.7.27-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  user-auth-service:
    image: randoi/user-auth-service:1.0
    container_name: user-auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_auth_db
    depends_on:
      - mysql
      - rabbitmq

  cinema-movie-service:
    image: randoi/cinema-movie-service:1.0
    container_name: cinema-movie-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cinema_movie_db
    depends_on:
      - mysql
      - rabbitmq

  notification-service:
    image: randoi/notification-service:1.0
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

volumes:
  mysql-data: